<?php

namespace Database\Seeders;

use App\Models\FeedIntakeMaster;
use Illuminate\Database\Seeder;

class FeedIntakeMasterSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'age' => 0,
                'feed_ah' => 4.50,
                'feed_male' => 0.00,
                'feed_female' => 0.00,
                'cum_feed_ah' => 4.5,
                'cum_feed_male' => 0,
                'cum_feed_female' => null,
                'weight_ah' => 37.8,
                'weight_male' => 37.8,
                'weight_female' => 37.8,
                'mortality_ah' => 0.1,
                'mortality_male' => 0.1,
                'mortality_female' => 0.1,
                'fcr_ah' => 0.1323,
                'fcr_male' => 0,
                'fcr_female' => 0.3292,
                'pi_ah' => null,
                'pi_male' => null,
                'pi_female' => null,
            ],
            [
                'age' => 1,
                'feed_ah' => 11.70,
                'feed_male' => 16.20,
                'feed_female' => 14.40,
                'cum_feed_ah' => 16.2,
                'cum_feed_male' => 16.2,
                'cum_feed_female' => 14.4,
                'weight_ah' => 49.5,
                'weight_male' => 50.4,
                'weight_female' => 48.6,
                'mortality_ah' => 0.25,
                'mortality_male' => 0.25,
                'mortality_female' => 0.25,
                'fcr_ah' => 0.3636,
                'fcr_male' => 0.3571,
                'fcr_female' => 0.5556,
                'pi_ah' => null,
                'pi_male' => null,
                'pi_female' => null,
            ],
            [
                'age' => 2,
                'feed_ah' => 18.90,
                'feed_male' => 18.90,
                'feed_female' => 17.10,
                'cum_feed_ah' => 35.1,
                'cum_feed_male' => 35.1,
                'cum_feed_female' => 31.5,
                'weight_ah' => 63.9,
                'weight_male' => 64.8,
                'weight_female' => 63,
                'mortality_ah' => 0.45,
                'mortality_male' => 0.45,
                'mortality_female' => 0.45,
                'fcr_ah' => 0.6103,
                'fcr_male' => 0.6019,
                'fcr_female' => 0.7323,
                'pi_ah' => 521,
                'pi_male' => 535,
                'pi_female' => 564,
            ],
            [
                'age' => 3,
                'feed_ah' => 21.60,
                'feed_male' => 20.70,
                'feed_female' => 20.70,
                'cum_feed_ah' => 56.7,
                'cum_feed_male' => 55.8,
                'cum_feed_female' => 52.2,
                'weight_ah' => 81,
                'weight_male' => 82.8,
                'weight_female' => 79.2,
                'mortality_ah' => 0.65,
                'mortality_male' => 0.65,
                'mortality_female' => 0.65,
                'fcr_ah' => 0.7778,
                'fcr_male' => 0.7488,
                'fcr_female' => 0.8485,
                'pi_ah' => 344,
                'pi_male' => 366,
                'pi_female' => 358,
            ],
            [
                'age' => 4,
                'feed_ah' => 23.40,
                'feed_male' => 22.50,
                'feed_female' => 23.40,
                'cum_feed_ah' => 80.1,
                'cum_feed_male' => 78.3,
                'cum_feed_female' => 75.6,
                'weight_ah' => 100.8,
                'weight_male' => 102.6,
                'weight_female' => 99,
                'mortality_ah' => 0.85,
                'mortality_male' => 0.85,
                'mortality_female' => 0.85,
                'fcr_ah' => 0.8829,
                'fcr_male' => 0.848,
                'fcr_female' => 0.9218,
                'pi_ah' => 282,
                'pi_male' => 299,
                'pi_female' => 289,
            ],
            [
                'age' => 5,
                'feed_ah' => 25.20,
                'feed_male' => 25.20,
                'feed_female' => 25.20,
                'cum_feed_ah' => 105.3,
                'cum_feed_male' => 103.5,
                'cum_feed_female' => 100.8,
                'weight_ah' => 124.2,
                'weight_male' => 126.9,
                'weight_female' => 121.5,
                'mortality_ah' => 1,
                'mortality_male' => 1,
                'mortality_female' => 1,
                'fcr_ah' => 0.942,
                'fcr_male' => 0.9062,
                'fcr_female' => 0.9562,
                'pi_ah' => 261,
                'pi_male' => 277,
                'pi_female' => 260,
            ],
            [
                'age' => 6,
                'feed_ah' => 27.00,
                'feed_male' => 27.90,
                'feed_female' => 27.00,
                'cum_feed_ah' => 132.3,
                'cum_feed_male' => 131.4,
                'cum_feed_female' => 127.8,
                'weight_ah' => 151.2,
                'weight_male' => 153.9,
                'weight_female' => 148.5,
                'mortality_ah' => 1.15,
                'mortality_male' => 1.15,
                'mortality_female' => 1.15,
                'fcr_ah' => 0.9722,
                'fcr_male' => 0.9487,
                'fcr_female' => 0.9827,
                'pi_ah' => 256,
                'pi_male' => 267,
                'pi_female' => 255,
            ],
            [
                'age' => 7,
                'feed_ah' => 29.70,
                'feed_male' => 32.40,
                'feed_female' => 30.60,
                'cum_feed_ah' => 162,
                'cum_feed_male' => 163.8,
                'cum_feed_female' => 158.4,
                'weight_ah' => 181.8,
                'weight_male' => 184.5,
                'weight_female' => 179.1,
                'mortality_ah' => 1.25,
                'mortality_male' => 1.25,
                'mortality_female' => 1.25,
                'fcr_ah' => 0.9901,
                'fcr_male' => 0.9864,
                'fcr_female' => 1.0169,
                'pi_ah' => 259,
                'pi_male' => 263,
                'pi_female' => 257,
            ],
            [
                'age' => 8,
                'feed_ah' => 36.00,
                'feed_male' => 36.00,
                'feed_female' => 36.00,
                'cum_feed_ah' => 198,
                'cum_feed_male' => 199.8,
                'cum_feed_female' => 194.4,
                'weight_ah' => 216,
                'weight_male' => 219.6,
                'weight_female' => 212.4,
                'mortality_ah' => 1.35,
                'mortality_male' => 1.35,
                'mortality_female' => 1.35,
                'fcr_ah' => 1.0185,
                'fcr_male' => 1.0109,
                'fcr_female' => 1.0386,
                'pi_ah' => 261,
                'pi_male' => 267,
                'pi_female' => 257,
            ],
            [
                'age' => 9,
                'feed_ah' => 39.60,
                'feed_male' => 40.50,
                'feed_female' => 37.80,
                'cum_feed_ah' => 237.6,
                'cum_feed_male' => 240.3,
                'cum_feed_female' => 232.2,
                'weight_ah' => 254.7,
                'weight_male' => 260.1,
                'weight_female' => 248.4,
                'mortality_ah' => 1.45,
                'mortality_male' => 1.45,
                'mortality_female' => 1.45,
                'fcr_ah' => 1.0365,
                'fcr_male' => 1.0265,
                'fcr_female' => 1.0625,
                'pi_ah' => 269,
                'pi_male' => 277,
                'pi_female' => 261,
            ],
            [
                'age' => 10,
                'feed_ah' => 45.00,
                'feed_male' => 46.80,
                'feed_female' => 43.20,
                'cum_feed_ah' => 282.6,
                'cum_feed_male' => 287.1,
                'cum_feed_female' => 275.4,
                'weight_ah' => 297,
                'weight_male' => 305.1,
                'weight_female' => 288,
                'mortality_ah' => 1.55,
                'mortality_male' => 1.55,
                'mortality_female' => 1.55,
                'fcr_ah' => 1.0572,
                'fcr_male' => 1.0456,
                'fcr_female' => 1.084,
                'pi_ah' => 276,
                'pi_male' => 287,
                'pi_female' => 266,
            ],
            [
                'age' => 11,
                'feed_ah' => 51.30,
                'feed_male' => 54.00,
                'feed_female' => 48.60,
                'cum_feed_ah' => 333.9,
                'cum_feed_male' => 341.1,
                'cum_feed_female' => 324,
                'weight_ah' => 343.8,
                'weight_male' => 355.5,
                'weight_female' => 332.1,
                'mortality_ah' => 1.65,
                'mortality_male' => 1.65,
                'mortality_female' => 1.65,
                'fcr_ah' => 1.0791,
                'fcr_male' => 1.0661,
                'fcr_female' => 1.1085,
                'pi_ah' => 284,
                'pi_male' => 298,
                'pi_female' => 273,
            ],
            [
                'age' => 12,
                'feed_ah' => 57.60,
                'feed_male' => 61.20,
                'feed_female' => 54.00,
                'cum_feed_ah' => 391.5,
                'cum_feed_male' => 402.3,
                'cum_feed_female' => 378,
                'weight_ah' => 396,
                'weight_male' => 411.3,
                'weight_female' => 378.9,
                'mortality_ah' => 1.85,
                'mortality_male' => 1.85,
                'mortality_female' => 1.85,
                'fcr_ah' => 1.0985,
                'fcr_male' => 1.0868,
                'fcr_female' => 1.132,
                'pi_ah' => 294,
                'pi_male' => 309,
                'pi_female' => 279,
            ],
            [
                'age' => 13,
                'feed_ah' => 65.70,
                'feed_male' => 70.20,
                'feed_female' => 60.30,
                'cum_feed_ah' => 457.2,
                'cum_feed_male' => 472.5,
                'cum_feed_female' => 438.3,
                'weight_ah' => 452.7,
                'weight_male' => 472.5,
                'weight_female' => 430.2,
                'mortality_ah' => 2.05,
                'mortality_male' => 2.05,
                'mortality_female' => 2.05,
                'fcr_ah' => 1.1222,
                'fcr_male' => 1.1111,
                'fcr_female' => 1.1566,
                'pi_ah' => 303,
                'pi_male' => 320,
                'pi_female' => 286,
            ],
            [
                'age' => 14,
                'feed_ah' => 72.00,
                'feed_male' => 81.00,
                'feed_female' => 64.80,
                'cum_feed_ah' => 529.2,
                'cum_feed_male' => 553.5,
                'cum_feed_female' => 503.1,
                'weight_ah' => 513,
                'weight_male' => 542.7,
                'weight_female' => 483.3,
                'mortality_ah' => 2.2,
                'mortality_male' => 2.2,
                'mortality_female' => 2.2,
                'fcr_ah' => 1.1462,
                'fcr_male' => 1.1332,
                'fcr_female' => 1.1814,
                'pi_ah' => 312,
                'pi_male' => 334,
                'pi_female' => 291,
            ],
            [
                'age' => 15,
                'feed_ah' => 75.60,
                'feed_male' => 80.10,
                'feed_female' => 72.00,
                'cum_feed_ah' => 604.8,
                'cum_feed_male' => 633.6,
                'cum_feed_female' => 575.1,
                'weight_ah' => 575.1,
                'weight_male' => 609.3,
                'weight_female' => 540.9,
                'mortality_ah' => 2.25,
                'mortality_male' => 2.25,
                'mortality_female' => 2.25,
                'fcr_ah' => 1.1685,
                'fcr_male' => 1.1554,
                'fcr_female' => 1.2077,
                'pi_ah' => 320,
                'pi_male' => 343,
                'pi_female' => 298,
            ],
            [
                'age' => 16,
                'feed_ah' => 81.90,
                'feed_male' => 86.40,
                'feed_female' => 77.40,
                'cum_feed_ah' => 686.7,
                'cum_feed_male' => 720,
                'cum_feed_female' => 652.5,
                'weight_ah' => 639.9,
                'weight_male' => 678.6,
                'weight_female' => 600.3,
                'mortality_ah' => 2.3,
                'mortality_male' => 2.3,
                'mortality_female' => 2.3,
                'fcr_ah' => 1.1924,
                'fcr_male' => 1.1789,
                'fcr_female' => 1.2332,
                'pi_ah' => 327,
                'pi_male' => 351,
                'pi_female' => 303,
            ],
            [
                'age' => 17,
                'feed_ah' => 88.20,
                'feed_male' => 92.70,
                'feed_female' => 83.70,
                'cum_feed_ah' => 774.9,
                'cum_feed_male' => 812.7,
                'cum_feed_female' => 736.2,
                'weight_ah' => 707.4,
                'weight_male' => 750.6,
                'weight_female' => 663.3,
                'mortality_ah' => 2.35,
                'mortality_male' => 2.35,
                'mortality_female' => 2.35,
                'fcr_ah' => 1.2171,
                'fcr_male' => 1.203,
                'fcr_female' => 1.2579,
                'pi_ah' => 333,
                'pi_male' => 358,
                'pi_female' => 308,
            ],
            [
                'age' => 18,
                'feed_ah' => 94.50,
                'feed_male' => 99.00,
                'feed_female' => 89.10,
                'cum_feed_ah' => 869.4,
                'cum_feed_male' => 911.7,
                'cum_feed_female' => 825.3,
                'weight_ah' => 777.6,
                'weight_male' => 826.2,
                'weight_female' => 729,
                'mortality_ah' => 2.4,
                'mortality_male' => 2.4,
                'mortality_female' => 2.4,
                'fcr_ah' => 1.2423,
                'fcr_male' => 1.2261,
                'fcr_female' => 1.2844,
                'pi_ah' => 339,
                'pi_male' => 365,
                'pi_female' => 314,
            ],
            [
                'age' => 19,
                'feed_ah' => 99.90,
                'feed_male' => 105.30,
                'feed_female' => 95.40,
                'cum_feed_ah' => 969.3,
                'cum_feed_male' => 1017,
                'cum_feed_female' => 920.7,
                'weight_ah' => 850.5,
                'weight_male' => 904.5,
                'weight_female' => 796.5,
                'mortality_ah' => 2.5,
                'mortality_male' => 2.45,
                'mortality_female' => 2.5,
                'fcr_ah' => 1.2663,
                'fcr_male' => 1.2493,
                'fcr_female' => 1.3096,
                'pi_ah' => 344,
                'pi_male' => 371,
                'pi_female' => 318,
            ],
            [
                'age' => 20,
                'feed_ah' => 106.20,
                'feed_male' => 111.60,
                'feed_female' => 100.80,
                'cum_feed_ah' => 1075.5,
                'cum_feed_male' => 1128.6,
                'cum_feed_female' => 1021.5,
                'weight_ah' => 926.1,
                'weight_male' => 985.5,
                'weight_female' => 866.7,
                'mortality_ah' => 2.6,
                'mortality_male' => 2.5,
                'mortality_female' => 2.6,
                'fcr_ah' => 1.2904,
                'fcr_male' => 1.2725,
                'fcr_female' => 1.3348,
                'pi_ah' => 349,
                'pi_male' => 377,
                'pi_female' => 322,
            ],
            [
                'age' => 21,
                'feed_ah' => 112.50,
                'feed_male' => 117.90,
                'feed_female' => 106.20,
                'cum_feed_ah' => 1188,
                'cum_feed_male' => 1246.5,
                'cum_feed_female' => 1127.7,
                'weight_ah' => 1004.4,
                'weight_male' => 1069.2,
                'weight_female' => 938.7,
                'mortality_ah' => 2.8,
                'mortality_male' => 2.55,
                'mortality_female' => 2.8,
                'fcr_ah' => 1.3142,
                'fcr_male' => 1.2954,
                'fcr_female' => 1.3588,
                'pi_ah' => 353,
                'pi_male' => 383,
                'pi_female' => 325,
            ],
            [
                'age' => 22,
                'feed_ah' => 117.90,
                'feed_male' => 124.20,
                'feed_female' => 111.60,
                'cum_feed_ah' => 1305.9,
                'cum_feed_male' => 1370.7,
                'cum_feed_female' => 1239.3,
                'weight_ah' => 1084.5,
                'weight_male' => 1155.6,
                'weight_female' => 1013.4,
                'mortality_ah' => 2.9,
                'mortality_male' => 2.6,
                'mortality_female' => 2.9,
                'fcr_ah' => 1.3379,
                'fcr_male' => 1.3179,
                'fcr_female' => 1.3838,
                'pi_ah' => 357,
                'pi_male' => 388,
                'pi_female' => 329,
            ],
            [
                'age' => 23,
                'feed_ah' => 123.30,
                'feed_male' => 129.60,
                'feed_female' => 117.00,
                'cum_feed_ah' => 1429.2,
                'cum_feed_male' => 1500.3,
                'cum_feed_female' => 1356.3,
                'weight_ah' => 1166.4,
                'weight_male' => 1243.8,
                'weight_female' => 1089,
                'mortality_ah' => 3,
                'mortality_male' => 2.65,
                'mortality_female' => 3,
                'fcr_ah' => 1.3615,
                'fcr_male' => 1.3402,
                'fcr_female' => 1.4075,
                'pi_ah' => 361,
                'pi_male' => 392,
                'pi_female' => 331,
            ],
            [
                'age' => 24,
                'feed_ah' => 128.70,
                'feed_male' => 135.90,
                'feed_female' => 122.40,
                'cum_feed_ah' => 1557.9,
                'cum_feed_male' => 1636.2,
                'cum_feed_female' => 1478.7,
                'weight_ah' => 1251,
                'weight_male' => 1333.8,
                'weight_female' => 1167.3,
                'mortality_ah' => 3.1,
                'mortality_male' => 2.7,
                'mortality_female' => 3.1,
                'fcr_ah' => 1.3837,
                'fcr_male' => 1.363,
                'fcr_female' => 1.4302,
                'pi_ah' => 365,
                'pi_male' => 396,
                'pi_female' => 334,
            ],
            [
                'age' => 25,
                'feed_ah' => 134.10,
                'feed_male' => 141.30,
                'feed_female' => 126.90,
                'cum_feed_ah' => 1692,
                'cum_feed_male' => 1777.5,
                'cum_feed_female' => 1605.6,
                'weight_ah' => 1337.4,
                'weight_male' => 1426.5,
                'weight_female' => 1247.4,
                'mortality_ah' => 3.15,
                'mortality_male' => 2.75,
                'mortality_female' => 3.15,
                'fcr_ah' => 1.4057,
                'fcr_male' => 1.3845,
                'fcr_female' => 1.4519,
                'pi_ah' => 368,
                'pi_male' => 400,
                'pi_female' => 337,
            ],
            [
                'age' => 26,
                'feed_ah' => 138.60,
                'feed_male' => 145.80,
                'feed_female' => 131.40,
                'cum_feed_ah' => 1830.6,
                'cum_feed_male' => 1923.3,
                'cum_feed_female' => 1737,
                'weight_ah' => 1424.7,
                'weight_male' => 1521,
                'weight_female' => 1329.3,
                'mortality_ah' => 3.2,
                'mortality_male' => 2.8,
                'mortality_female' => 3.2,
                'fcr_ah' => 1.4277,
                'fcr_male' => 1.405,
                'fcr_female' => 1.4737,
                'pi_ah' => 371,
                'pi_male' => 404,
                'pi_female' => 340,
            ],
            [
                'age' => 27,
                'feed_ah' => 144.00,
                'feed_male' => 151.20,
                'feed_female' => 135.90,
                'cum_feed_ah' => 1974.6,
                'cum_feed_male' => 2074.5,
                'cum_feed_female' => 1872.9,
                'weight_ah' => 1513.8,
                'weight_male' => 1616.4,
                'weight_female' => 1412.1,
                'mortality_ah' => 3.25,
                'mortality_male' => 2.85,
                'mortality_female' => 3.25,
                'fcr_ah' => 1.4493,
                'fcr_male' => 1.426,
                'fcr_female' => 1.4955,
                'pi_ah' => 374,
                'pi_male' => 407,
                'pi_female' => 343,
            ],
            [
                'age' => 28,
                'feed_ah' => 148.50,
                'feed_male' => 155.70,
                'feed_female' => 140.40,
                'cum_feed_ah' => 2123.1,
                'cum_feed_male' => 2230.2,
                'cum_feed_female' => 2013.3,
                'weight_ah' => 1604.7,
                'weight_male' => 1713.6,
                'weight_female' => 1495.8,
                'mortality_ah' => 3.3,
                'mortality_male' => 2.9,
                'mortality_female' => 3.35,
                'fcr_ah' => 1.4701,
                'fcr_male' => 1.4461,
                'fcr_female' => 1.5165,
                'pi_ah' => 376,
                'pi_male' => 410,
                'pi_female' => 345,
            ],
            [
                'age' => 29,
                'feed_ah' => 152.10,
                'feed_male' => 160.20,
                'feed_female' => 144.90,
                'cum_feed_ah' => 2275.2,
                'cum_feed_male' => 2390.4,
                'cum_feed_female' => 2158.2,
                'weight_ah' => 1697.4,
                'weight_male' => 1812.6,
                'weight_female' => 1581.3,
                'mortality_ah' => 3.35,
                'mortality_male' => 2.95,
                'mortality_female' => 3.45,
                'fcr_ah' => 1.4893,
                'fcr_male' => 1.4653,
                'fcr_female' => 1.5368,
                'pi_ah' => 379,
                'pi_male' => 413,
                'pi_female' => 347,
            ],
            [
                'age' => 30,
                'feed_ah' => 156.60,
                'feed_male' => 164.70,
                'feed_female' => 148.50,
                'cum_feed_ah' => 2431.8,
                'cum_feed_male' => 2555.1,
                'cum_feed_female' => 2306.7,
                'weight_ah' => 1790.1,
                'weight_male' => 1912.5,
                'weight_female' => 1667.7,
                'mortality_ah' => 3.4,
                'mortality_male' => 3,
                'mortality_female' => 3.55,
                'fcr_ah' => 1.5094,
                'fcr_male' => 1.4844,
                'fcr_female' => 1.5559,
                'pi_ah' => 381,
                'pi_male' => 416,
                'pi_female' => 348,
            ],
            [
                'age' => 31,
                'feed_ah' => 160.20,
                'feed_male' => 169.20,
                'feed_female' => 152.10,
                'cum_feed_ah' => 2592,
                'cum_feed_male' => 2724.3,
                'cum_feed_female' => 2458.8,
                'weight_ah' => 1884.6,
                'weight_male' => 2013.3,
                'weight_female' => 1755.9,
                'mortality_ah' => 3.45,
                'mortality_male' => 3.05,
                'mortality_female' => 3.65,
                'fcr_ah' => 1.5282,
                'fcr_male' => 1.5035,
                'fcr_female' => 1.5753,
                'pi_ah' => 384,
                'pi_male' => 418,
                'pi_female' => 350,
            ],
            [
                'age' => 32,
                'feed_ah' => 164.70,
                'feed_male' => 172.80,
                'feed_female' => 155.70,
                'cum_feed_ah' => 2756.7,
                'cum_feed_male' => 2897.1,
                'cum_feed_female' => 2614.5,
                'weight_ah' => 1980,
                'weight_male' => 2115,
                'weight_female' => 1844.1,
                'mortality_ah' => 3.5,
                'mortality_male' => 3.1,
                'mortality_female' => 3.75,
                'fcr_ah' => 1.547,
                'fcr_male' => 1.522,
                'fcr_female' => 1.5942,
                'pi_ah' => 385,
                'pi_male' => 420,
                'pi_female' => 352,
            ],
            [
                'age' => 33,
                'feed_ah' => 168.30,
                'feed_male' => 176.40,
                'feed_female' => 159.30,
                'cum_feed_ah' => 2925,
                'cum_feed_male' => 3073.5,
                'cum_feed_female' => 2773.8,
                'weight_ah' => 2075.4,
                'weight_male' => 2217.6,
                'weight_female' => 1933.2,
                'mortality_ah' => 3.55,
                'mortality_male' => 3.15,
                'mortality_female' => 3.85,
                'fcr_ah' => 1.566,
                'fcr_male' => 1.54,
                'fcr_female' => 1.6128,
                'pi_ah' => 387,
                'pi_male' => 422,
                'pi_female' => 353,
            ],
            [
                'age' => 34,
                'feed_ah' => 171.90,
                'feed_male' => 180.00,
                'feed_female' => 162.90,
                'cum_feed_ah' => 3096.9,
                'cum_feed_male' => 3253.5,
                'cum_feed_female' => 2936.7,
                'weight_ah' => 2171.7,
                'weight_male' => 2321.1,
                'weight_female' => 2023.2,
                'mortality_ah' => 3.65,
                'mortality_male' => 3.25,
                'mortality_female' => 3.95,
                'fcr_ah' => 1.5845,
                'fcr_male' => 1.5575,
                'fcr_female' => 1.6316,
                'pi_ah' => 388,
                'pi_male' => 424,
                'pi_female' => 354,
            ],
            [
                'age' => 35,
                'feed_ah' => 174.60,
                'feed_male' => 183.60,
                'feed_female' => 166.50,
                'cum_feed_ah' => 3271.5,
                'cum_feed_male' => 3437.1,
                'cum_feed_female' => 3103.2,
                'weight_ah' => 2268.9,
                'weight_male' => 2424.6,
                'weight_female' => 2113.2,
                'mortality_ah' => 3.8,
                'mortality_male' => 3.35,
                'mortality_female' => 4.1,
                'fcr_ah' => 1.6021,
                'fcr_male' => 1.5751,
                'fcr_female' => 1.6503,
                'pi_ah' => 389,
                'pi_male' => 425,
                'pi_female' => 354,
            ],
            [
                'age' => 36,
                'feed_ah' => 178.20,
                'feed_male' => 187.20,
                'feed_female' => 169.20,
                'cum_feed_ah' => 3449.7,
                'cum_feed_male' => 3624.3,
                'cum_feed_female' => 3272.4,
                'weight_ah' => 2366.1,
                'weight_male' => 2529,
                'weight_female' => 2203.2,
                'mortality_ah' => 3.95,
                'mortality_male' => 3.45,
                'mortality_female' => 4.25,
                'fcr_ah' => 1.62,
                'fcr_male' => 1.5923,
                'fcr_female' => 1.6686,
                'pi_ah' => 389,
                'pi_male' => 425,
                'pi_female' => 355,
            ],
            [
                'age' => 37,
                'feed_ah' => 181.80,
                'feed_male' => 190.80,
                'feed_female' => 172.80,
                'cum_feed_ah' => 3631.5,
                'cum_feed_male' => 3815.1,
                'cum_feed_female' => 3445.2,
                'weight_ah' => 2464.2,
                'weight_male' => 2633.4,
                'weight_female' => 2294.1,
                'mortality_ah' => 4.1,
                'mortality_male' => 3.55,
                'mortality_female' => 4.4,
                'fcr_ah' => 1.6374,
                'fcr_male' => 1.6097,
                'fcr_female' => 1.6872,
                'pi_ah' => 390,
                'pi_male' => 426,
                'pi_female' => 355,
            ],
            [
                'age' => 38,
                'feed_ah' => 185.40,
                'feed_male' => 193.50,
                'feed_female' => 176.40,
                'cum_feed_ah' => 3816.9,
                'cum_feed_male' => 4008.6,
                'cum_feed_female' => 3621.6,
                'weight_ah' => 2561.4,
                'weight_male' => 2737.8,
                'weight_female' => 2385,
                'mortality_ah' => 4.25,
                'mortality_male' => 3.65,
                'mortality_female' => 4.55,
                'fcr_ah' => 1.6557,
                'fcr_male' => 1.6269,
                'fcr_female' => 1.7056,
                'pi_ah' => 389,
                'pi_male' => 426,
                'pi_female' => 355,
            ],
            [
                'age' => 39,
                'feed_ah' => 188.10,
                'feed_male' => 197.10,
                'feed_female' => 179.10,
                'cum_feed_ah' => 4005,
                'cum_feed_male' => 4205.7,
                'cum_feed_female' => 3800.7,
                'weight_ah' => 2658.6,
                'weight_male' => 2842.2,
                'weight_female' => 2475.9,
                'mortality_ah' => 4.4,
                'mortality_male' => 3.75,
                'mortality_female' => 4.7,
                'fcr_ah' => 1.6738,
                'fcr_male' => 1.6441,
                'fcr_female' => 1.7243,
                'pi_ah' => 389,
                'pi_male' => 426,
                'pi_female' => 354,
            ],
            [
                'age' => 40,
                'feed_ah' => 191.70,
                'feed_male' => 200.70,
                'feed_female' => 182.70,
                'cum_feed_ah' => 4196.7,
                'cum_feed_male' => 4406.4,
                'cum_feed_female' => 3983.4,
                'weight_ah' => 2755.8,
                'weight_male' => 2946.6,
                'weight_female' => 2566.8,
                'mortality_ah' => 4.55,
                'mortality_male' => 3.85,
                'mortality_female' => 4.85,
                'fcr_ah' => 1.6921,
                'fcr_male' => 1.6616,
                'fcr_female' => 1.7438,
                'pi_ah' => 388,
                'pi_male' => 426,
                'pi_female' => 354,
            ],
            [
                'age' => 41,
                'feed_ah' => 195.30,
                'feed_male' => 203.40,
                'feed_female' => 186.30,
                'cum_feed_ah' => 4392,
                'cum_feed_male' => 4609.8,
                'cum_feed_female' => 4169.7,
                'weight_ah' => 2853,
                'weight_male' => 3050.1,
                'weight_female' => 2656.8,
                'mortality_ah' => 4.7,
                'mortality_male' => 3.95,
                'mortality_female' => 5,
                'fcr_ah' => 1.7105,
                'fcr_male' => 1.6793,
                'fcr_female' => 1.7631,
                'pi_ah' => 387,
                'pi_male' => 425,
                'pi_female' => 353,
            ],
            [
                'age' => 42,
                'feed_ah' => 198.00,
                'feed_male' => 207.00,
                'feed_female' => 189.00,
                'cum_feed_ah' => 4590,
                'cum_feed_male' => 4816.8,
                'cum_feed_female' => 4358.7,
                'weight_ah' => 2950.2,
                'weight_male' => 3152.7,
                'weight_female' => 2746.8,
                'mortality_ah' => 4.85,
                'mortality_male' => 4.05,
                'mortality_female' => 5.15,
                'fcr_ah' => 1.7287,
                'fcr_male' => 1.6976,
                'fcr_female' => 1.7832,
                'pi_ah' => 386,
                'pi_male' => 424,
                'pi_female' => 351,
            ],
            [
                'age' => 43,
                'feed_ah' => 201.60,
                'feed_male' => 210.60,
                'feed_female' => 192.60,
                'cum_feed_ah' => 4791.6,
                'cum_feed_male' => 5027.4,
                'cum_feed_female' => 4551.3,
                'weight_ah' => 3045.6,
                'weight_male' => 3255.3,
                'weight_female' => 2835.9,
                'mortality_ah' => 5,
                'mortality_male' => 4.15,
                'mortality_female' => 5.3,
                'fcr_ah' => 1.7481,
                'fcr_male' => 1.716,
                'fcr_female' => 1.8034,
                'pi_ah' => 384,
                'pi_male' => 422,
                'pi_female' => 350,
            ],
            [
                'age' => 44,
                'feed_ah' => 205.20,
                'feed_male' => 213.30,
                'feed_female' => 196.20,
                'cum_feed_ah' => 4996.8,
                'cum_feed_male' => 5240.7,
                'cum_feed_female' => 4747.5,
                'weight_ah' => 3141,
                'weight_male' => 3357,
                'weight_female' => 2925,
                'mortality_ah' => 5.15,
                'mortality_male' => 4.25,
                'mortality_female' => 5.45,
                'fcr_ah' => 1.7676,
                'fcr_male' => 1.7346,
                'fcr_female' => 1.8243,
                'pi_ah' => 383,
                'pi_male' => 421,
                'pi_female' => 348,
            ],
            [
                'age' => 45,
                'feed_ah' => 208.80,
                'feed_male' => 216.90,
                'feed_female' => 199.80,
                'cum_feed_ah' => 5205.6,
                'cum_feed_male' => 5457.6,
                'cum_feed_female' => 4947.3,
                'weight_ah' => 3235.5,
                'weight_male' => 3457.8,
                'weight_female' => 3013.2,
                'mortality_ah' => 5.3,
                'mortality_male' => 4.4,
                'mortality_female' => 5.6,
                'fcr_ah' => 1.7877,
                'fcr_male' => 1.7537,
                'fcr_female' => 1.8458,
                'pi_ah' => 380,
                'pi_male' => 418,
                'pi_female' => 346,
            ],
            [
                'age' => 46,
                'feed_ah' => 212.40,
                'feed_male' => 220.50,
                'feed_female' => 203.40,
                'cum_feed_ah' => 5418,
                'cum_feed_male' => 5678.1,
                'cum_feed_female' => 5150.7,
                'weight_ah' => 3329.1,
                'weight_male' => 3556.8,
                'weight_female' => 3100.5,
                'mortality_ah' => 5.45,
                'mortality_male' => 4.55,
                'mortality_female' => 5.75,
                'fcr_ah' => 1.8083,
                'fcr_male' => 1.7738,
                'fcr_female' => 1.8685,
                'pi_ah' => 378,
                'pi_male' => 416,
                'pi_female' => 344,
            ],
            [
                'age' => 47,
                'feed_ah' => 215.10,
                'feed_male' => 223.20,
                'feed_female' => 207.00,
                'cum_feed_ah' => 5633.1,
                'cum_feed_male' => 5901.3,
                'cum_feed_female' => 5357.7,
                'weight_ah' => 3420.9,
                'weight_male' => 3655.8,
                'weight_female' => 3186,
                'mortality_ah' => 5.6,
                'mortality_male' => 4.7,
                'mortality_female' => 5.9,
                'fcr_ah' => 1.8296,
                'fcr_male' => 1.7936,
                'fcr_female' => 1.8912,
                'pi_ah' => 375,
                'pi_male' => 413,
                'pi_female' => 341,
            ],
            [
                'age' => 48,
                'feed_ah' => 218.70,
                'feed_male' => 226.80,
                'feed_female' => 210.60,
                'cum_feed_ah' => 5851.8,
                'cum_feed_male' => 6128.1,
                'cum_feed_female' => 5568.3,
                'weight_ah' => 3511.8,
                'weight_male' => 3752.1,
                'weight_female' => 3271.5,
                'mortality_ah' => 5.75,
                'mortality_male' => 4.85,
                'mortality_female' => 6.05,
                'fcr_ah' => 1.8515,
                'fcr_male' => 1.8147,
                'fcr_female' => 1.9149,
                'pi_ah' => 372,
                'pi_male' => 409,
                'pi_female' => 338,
            ],
            [
                'age' => 49,
                'feed_ah' => 222.30,
                'feed_male' => 229.50,
                'feed_female' => 214.20,
                'cum_feed_ah' => 6074.1,
                'cum_feed_male' => 6357.6,
                'cum_feed_female' => 5782.5,
                'weight_ah' => 3600.9,
                'weight_male' => 3847.5,
                'weight_female' => 3355.2,
                'mortality_ah' => 5.9,
                'mortality_male' => 5,
                'mortality_female' => 6.2,
                'fcr_ah' => 1.8743,
                'fcr_male' => 1.836,
                'fcr_female' => 1.9397,
                'pi_ah' => 368,
                'pi_male' => 406,
                'pi_female' => 335,
            ],
            [
                'age' => 50,
                'feed_ah' => 225.00,
                'feed_male' => 232.20,
                'feed_female' => 217.80,
                'cum_feed_ah' => 6299.1,
                'cum_feed_male' => 6589.8,
                'cum_feed_female' => 6000.3,
                'weight_ah' => 3689.1,
                'weight_male' => 3941.1,
                'weight_female' => 3437.1,
                'mortality_ah' => 6,
                'mortality_male' => 5.1,
                'mortality_female' => 6.3,
                'fcr_ah' => 1.8972,
                'fcr_male' => 1.8579,
                'fcr_female' => 1.9647,
                'pi_ah' => 365,
                'pi_male' => 402,
                'pi_female' => 332,
            ],
            [
                'age' => 51,
                'feed_ah' => 227.70,
                'feed_male' => 234.90,
                'feed_female' => 220.50,
                'cum_feed_ah' => 6526.8,
                'cum_feed_male' => 6824.7,
                'cum_feed_female' => 6220.8,
                'weight_ah' => 3775.5,
                'weight_male' => 4032.9,
                'weight_female' => 3518.1,
                'mortality_ah' => 6.1,
                'mortality_male' => 5.2,
                'mortality_female' => 6.4,
                'fcr_ah' => 1.9208,
                'fcr_male' => 1.8803,
                'fcr_female' => 1.9907,
                'pi_ah' => 361,
                'pi_male' => 398,
                'pi_female' => 328,
            ],
            [
                'age' => 52,
                'feed_ah' => 230.40,
                'feed_male' => 236.70,
                'feed_female' => 224.10,
                'cum_feed_ah' => 6757.2,
                'cum_feed_male' => 7061.4,
                'cum_feed_female' => 6444.9,
                'weight_ah' => 3860.1,
                'weight_male' => 4122,
                'weight_female' => 3597.3,
                'mortality_ah' => 6.2,
                'mortality_male' => 5.3,
                'mortality_female' => 6.5,
                'fcr_ah' => 1.945,
                'fcr_male' => 1.9034,
                'fcr_female' => 2.0173,
                'pi_ah' => 357,
                'pi_male' => 394,
                'pi_female' => 324,
            ],
            [
                'age' => 53,
                'feed_ah' => 232.20,
                'feed_male' => 238.50,
                'feed_female' => 226.80,
                'cum_feed_ah' => 6989.4,
                'cum_feed_male' => 7299.9,
                'cum_feed_female' => 6671.7,
                'weight_ah' => 3942,
                'weight_male' => 4209.3,
                'weight_female' => 3674.7,
                'mortality_ah' => 6.3,
                'mortality_male' => 5.4,
                'mortality_female' => 6.6,
                'fcr_ah' => 1.9701,
                'fcr_male' => 1.9269,
                'fcr_female' => 2.0444,
                'pi_ah' => 353,
                'pi_male' => 389,
                'pi_female' => 321,
            ],
            [
                'age' => 54,
                'feed_ah' => 234.00,
                'feed_male' => 239.40,
                'feed_female' => 228.60,
                'cum_feed_ah' => 7223.4,
                'cum_feed_male' => 7539.3,
                'cum_feed_female' => 6900.3,
                'weight_ah' => 4023,
                'weight_male' => 4294.8,
                'weight_female' => 3750.3,
                'mortality_ah' => 6.45,
                'mortality_male' => 5.55,
                'mortality_female' => 6.75,
                'fcr_ah' => 1.995,
                'fcr_male' => 1.9505,
                'fcr_female' => 2.0719,
                'pi_ah' => 349,
                'pi_male' => 385,
                'pi_female' => 316,
            ],
            [
                'age' => 55,
                'feed_ah' => 234.90,
                'feed_male' => 239.40,
                'feed_female' => 230.40,
                'cum_feed_ah' => 7458.3,
                'cum_feed_male' => 7778.7,
                'cum_feed_female' => 7130.7,
                'weight_ah' => 4101.3,
                'weight_male' => 4377.6,
                'weight_female' => 3824.1,
                'mortality_ah' => 6.6,
                'mortality_male' => 5.7,
                'mortality_female' => 6.9,
                'fcr_ah' => 2.0206,
                'fcr_male' => 1.9744,
                'fcr_female' => 2.0995,
                'pi_ah' => 344,
                'pi_male' => 380,
                'pi_female' => 312,
            ],
            [
                'age' => 56,
                'feed_ah' => 235.80,
                'feed_male' => 239.40,
                'feed_female' => 231.30,
                'cum_feed_ah' => 7694.1,
                'cum_feed_male' => 8018.1,
                'cum_feed_female' => 7362,
                'weight_ah' => 4176.9,
                'weight_male' => 4457.7,
                'weight_female' => 3896.1,
                'mortality_ah' => 6.75,
                'mortality_male' => 5.85,
                'mortality_female' => 7.05,
                'fcr_ah' => 2.0467,
                'fcr_male' => 1.9986,
                'fcr_female' => null,
                'pi_ah' => 339,
                'pi_male' => 374,
                'pi_female' => 308,
            ]
        ];

        // Clear existing master data first to avoid duplicates
        FeedIntakeMaster::query()->truncate();

        foreach ($data as $item) {
            FeedIntakeMaster::query()->create($item);
        }
    }
}
